/*
 * This file re-exports selected icons from 'lucide-react'.
 * This is the single place to manage which lucide-react icons are available globally.
 * Editing the list of exports here will automatically update their availability
 * in globalLucideIcons.
 */
export {
    AlbumIcon,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Bitcoin,
    Binary,
    Building2,
    Bug,
    Circle,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Cpu,
    ComponentIcon,
    DatabaseZap,
    Dot,
    Download,
    FileLock2,
    Fingerprint,
    FileText,
    GitPullRequestArrow,
    Globe,
    GlobeLock,
    GripVertical,
    HandHeart,
    Handshake,
    Highlighter,
    HousePlus,
    LibraryIcon,
    Layout,
    LayoutTemplate,
    Loader2,
    MoreHorizontal,
    Pencil,
    PanelLeft,
    PanelsTopLeft,
    ReceiptText,
    Regex,
    Search,
    Share,
    SquareTerminal,
    Server,
    SplinePointer,
    Scale,
    ShieldUser,
    Tablets,
    Terminal,
    X,
    Zap
} from 'lucide-react'; 